"""
Integration test using a real machine learning model.

This test validates the integration between:

TrainingManager
↓
ModelFactory
↓
LinearRegressionModel
↓
PredictPipeline
↓
Forecaster
↓
EvaluatePipeline
↓
ModelEvaluator

Unlike tests that use fake models, this test uses the real
LinearRegressionModel implementation.
"""

from __future__ import annotations

import numpy as np
import pandas as pd

from src.ml.evaluation import ModelEvaluator
from src.ml.forecast import Forecaster
from src.ml.training.model_selection import ModelSelector
from src.ml.training.training_manager import TrainingManager
from src.pipelines.evaluate_pipeline import EvaluatePipeline
from src.pipelines.predict_pipeline import PredictPipeline


class LinearOnlyModelSelector(ModelSelector):
    """
    Model selector restricted to the linear regression model.

    The real ModelFactory and LinearRegressionModel are still used.
    Only model selection is controlled to keep the integration test
    independent from the application's global model configuration.
    """

    def resolve(self) -> tuple[str, ...]:
        """Return only the linear regression model."""

        return ("linear_regression",)


def _build_training_data() -> tuple[pd.DataFrame, pd.Series]:
    """
    Build deterministic training data.

    The target follows:

        y = 2 * feature_a + 3 * feature_b + 10
    """

    X = pd.DataFrame(
        {
            "feature_a": [1.0, 2.0, 3.0, 4.0, 5.0],
            "feature_b": [5.0, 4.0, 3.0, 2.0, 1.0],
        },
    )

    y = pd.Series(
        [
            27.0,
            26.0,
            25.0,
            24.0,
            23.0,
        ],
        name="target",
    )

    return X, y


def _build_prediction_features() -> pd.DataFrame:
    """Build deterministic prediction features."""

    return pd.DataFrame(
        {
            "feature_a": [6.0, 7.0, 8.0],
            "feature_b": [0.0, -1.0, -2.0],
        },
    )


def test_real_model_pipeline_trains_predicts_and_evaluates() -> None:
    """
    Validate the complete real-model execution flow.

    The test verifies that:

    1. TrainingManager creates the real LinearRegressionModel.
    2. The model is actually fitted.
    3. PredictPipeline generates predictions through Forecaster.
    4. EvaluatePipeline evaluates those predictions.
    5. The resulting metric is effectively zero for deterministic
       data generated by the same linear relationship.
    """

    # ----------------------------------------------------------
    # Arrange
    # ----------------------------------------------------------

    X_train, y_train = _build_training_data()
    X_test = _build_prediction_features()

    training_manager = TrainingManager(
        selector=LinearOnlyModelSelector(),
    )

    # ----------------------------------------------------------
    # Train
    # ----------------------------------------------------------

    training_result = training_manager.train(
        X_train,
        y_train,
    )

    assert "linear_regression" in training_result.models

    model = training_result.models[
        "linear_regression"
    ]

    assert model.is_fitted

    # ----------------------------------------------------------
    # Predict
    # ----------------------------------------------------------

    forecaster = Forecaster(
        model=model,
    )

    predict_pipeline = PredictPipeline(
        forecaster=forecaster,
    )

    prediction_result = predict_pipeline.run(
        models={
            "linear_regression": model,
        },
        features=X_test,
    )

    predictions = prediction_result.predictions

    assert "linear_regression" in predictions

    y_pred = predictions[
        "linear_regression"
    ]

    assert isinstance(
        y_pred,
        pd.Series,
    )

    assert len(y_pred) == len(X_test)

    assert y_pred.index.equals(
        X_test.index,
    )

    # Expected values from:
    #
    # y = 2 * feature_a + 3 * feature_b + 10
    #
    # (6, 0)  -> 22
    # (7, -1) -> 21
    # (8, -2) -> 20

    expected_predictions = pd.Series(
        [22.0, 21.0, 20.0],
        index=X_test.index,
        name="prediction",
    )

    np.testing.assert_allclose(
        y_pred.to_numpy(),
        expected_predictions.to_numpy(),
        rtol=1e-10,
        atol=1e-10,
    )

    # ----------------------------------------------------------
    # Evaluate
    # ----------------------------------------------------------

    y_test = expected_predictions.rename(
        "target",
    )

    evaluator = ModelEvaluator(
        metric="mae",
    )

    evaluate_pipeline = EvaluatePipeline(
        evaluator=evaluator,
    )

    evaluation_result = evaluate_pipeline.run(
        y_true=y_test,
        predictions=predictions,
    )

    assert "linear_regression" in (
        evaluation_result.metrics
    )

    metric = evaluation_result.metrics[
        "linear_regression"
    ]

    assert metric == 0.0

